var $ = require('jquery');
var modal = require('modal');

$(document).ready(function() {
    
    // isn't this pretty messy?
    // take a look at the "modal" module implementation, it uses an html template
    // and jQuery to create some brand new DOM elements!
    var $row = $('<div class="row">');
    var $col = $('<div class="col-xs-12 text-center">');
    var $btn = $('<button class="btn btn-primary">I was added with jQuery!<hr><b>Click Me!</b></button>');
    $('.row').last().after($row.append($col.append($btn))).after('<hr>');
    
    // display a modal window when clicking the button!
    $btn.on('click', function() {
        modal.show(
            'Using jQuery within Modules', 
            '<p>This modal was generated by a <em>Workspace</em> module using <em>Twitter Bootstrap\'s Modal plugin</em>.</p>'
        );
    });
    
});
